### ISSUE TITLE
Question on Callback

### ISSUE THREAD

**Issue by harikt** [undercloud/beacon#1]
Hi, 

Nice to see Beacon. I have a question when browsing through the docs and code. How will you handle the class ( controller ) if it has some dependencies in constructor ? Do you want to provide something like 

``` php
function () {
    return new Somecontroller($andDependencies);
}
```

EDIT : In that case I am not sure how we could pass the method though.

or is there a different way ?

Good work on Beacon.

Thank you.

**Comment by undercloud** [comment]
Hi, thanks for rating! 
Router performs one task - accept request and return info associated with it, nothing more.
For handling callback you need third party Dependency Injection manager (in this time I work on my own realization of DI),
With DI yot can process request like this:

``` PHP
$router
    ->get('/article/:id', 'ControllerArticle::getArticle');
...

$route = $router->go('/article/182');

$callback = $route->getCallback();

$di = new DependencyInjectionManager;

$di->resolve($callback);

```

``` PHP
class DependencyInjectionManager
{
    public function resolve($callback)
    {
        /* TODO
         *
         * 1) create instance
         * 2) parse method arguments
         * 3) resolve arguments
         * 4) call method
         */
    }
}
```

Middleware also need third party handler

**Comment by harikt** [comment]
Hey @undercloud ,

Cool. Thanks for the information.
